# Generated by Django 4.2.17 on 2025-01-18 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(choices=[('FIAT', 'FIAT'), ('CHEVROLET', 'CHEVROLET'), ('FORD', 'FORD'), ('TOYOTA', 'TOYOTA')], default='FORD', max_length=20, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('serial_carroceria', models.CharField(max_length=50, verbose_name='Serial Carroceria')),
                ('serial_motor', models.CharField(max_length=50, verbose_name='Serial Motor')),
                ('categoria', models.CharField(choices=[('PARTICULAR', 'PARTICULAR'), ('TRANSPORTE', 'TRANSPORTE'), ('DE CARGA', 'DE CARGA')], default='PARTICULAR', max_length=20, verbose_name='Categoria')),
                ('precio', models.IntegerField(verbose_name='Precio')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha Registro')),
                ('fecha_modificado', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
            ],
        ),
    ]
