# Generated by Django 4.2.17 on 2025-01-20 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiculo',
            options={'ordering': ['marca'], 'permissions': [('visualizar_catalogo', 'Puede visualizar Catálogo de Vehículos')], 'verbose_name': 'Vehiculo', 'verbose_name_plural': 'Vehiculos'},
        ),
    ]
